############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Activiteiten"
url = "activities/"
weight = 2

[[main]]
url = "partners_and_sponsors/"
name = "Partners en sponsoren"
weight = 3

[[main]]
url = "https://shop.svpromptusimperii.nl"
name = "Shop"
weight = 4

[[main]]
url = "about/"
name = "Over ons"
weight = 5


# footer menu
[[footer]]
name = "Over"
url = "about/"
weight = 1

[[footer]]
name = "Algemene voorwaarden"
url = "terms-and-conditions/"
weight = 2
