############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Over"
url = "about/"
weight = 2

[[main]]
name = "Elementen"
url = "elements/"
weight = 3

[[main]]
weight = 4
name = "Pagina's"
hasChildren = true

[[main]]
parent = "Pagina's"
name = "Blog"
url = "blog/"

[[main]]
parent = "Pagina's"
name = "Contact"
url = "contact/"

[[main]]
parent = "Pagina's"
name = "Auteurs"
url = "authors/"

[[main]]
parent = "Paginas"
name = "Categorieën"
url = "categories/"

[[main]]
parent = "Pagina's"
name = "404 Pagina"
url = "404/"


# footer menu
[[footer]]
name = "Over"
url = "about/"
weight = 1

[[footer]]
name = "Elementen"
url = "elements/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
