############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Activiteiten"
url = "activities/"
weight = 2

[[main]]
url = "partners_and_sponsors"
name = "Partners en sponsoren"
weight = 3

[[main]]
url = "about/"
name = "Over ons"
weight = 4


# footer menu
[[footer]]
name = "Over"
url = "about/"
weight = 1

[[footer]]
name = "Elementen"
url = "elements/"
weight = 2

[[footer]]
name = "Algemene voorwaarden"
url = "tos/"
weight = 3
